name: Ruby

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.5
    - name: Budle install
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
    - name: Setup Database
      run: |
        cp config/database.yml.ci config/database.yml
        sudo /etc/init.d/mysql start 
        bundle exec rake db:create
        bundle exec rake db:schema:load
      env:
        RAILS_ENV: test
    - name: test with Rake
      run: |
        bundle exec rake
      env:
        RAILS_ENV: test